"""Apply and verify one recorded natural-language configuration extension.

Only JSON append/replace/create data operations are accepted. Every invocation
uses a new directory beneath build/beverage-nl-extension, preserves raw output,
and checks frozen engineering requirements before running the virtual line.
"""
import copy
from collections import Counter
from datetime import datetime, timezone
import difflib
import hashlib
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "examples/beverage_nl_extension"
BASELINE = ROOT / "examples/beverage_full/example4"
REFERENCE = ROOT / "examples/beverage_full/example5/legacy"
VARIABLES = "system_variables.json"
GROUP = "layered/L3_group/run_recipe.group.json"
# Frozen evaluator references: not generated by the model in this demonstration.
REFERENCE_SHA256 = {
    "orange": "c644f87b2e3e7a7597713bfc847b11f158374e833005811fb6281ea97e2aecdb",
    "apple": "8b1b01d1faeea70cd9ab8d95ff2626b24e52536dc6f4d54c5fff0f48e0471646",
    "grape": "83990d587a60ed88fb36c7c0760c1282d84c0d39294ce27dba5232487f30b0ed",
}
REFERENCE_NORMALIZED_SHA256 = {
    "orange": "31a771c7a0a94ba3d4eb22ef55852212a04de9800b797fd9127b6a636a615269",
    "apple": "4f94f53cad4e9d45249a71b35dac7fd4918bd4804072648d468351c460a4af46",
    "grape": "46b4cad5b659fa0c88d76284fcee2487eadc3e1769153aa14a227e73575d2e9e",
}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def frozen_hash(path, recorded_bytes, recorded_normalized):
    actual = Path(path).read_bytes()
    if hashlib.sha256(actual).hexdigest() == recorded_bytes:
        return "original bytes"
    require(hashlib.sha256(actual.replace(b"\r\n", b"\n")).hexdigest() == recorded_normalized,
            "Frozen hash mismatch: " + str(path))
    return "CRLF/LF normalized replay"


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, "Duplicate JSON object key: " + key)
        result[key] = value
    return result


def read(path):
    def invalid_constant(value):
        raise ValueError("Nonstandard JSON number: " + value)
    return json.loads(Path(path).read_text(encoding="utf-8-sig"),
                      object_pairs_hook=unique_object, parse_constant=invalid_constant)


def write(path, value, indent=2):
    Path(path).write_text(json.dumps(value, ensure_ascii=False, indent=indent, allow_nan=False) + "\n",
                          encoding="utf-8", newline="\n")


def identical(a, b):
    # Unlike Python ==, distinguish true/1 and 1.0/1 in typed configuration data.
    return json.dumps(a, sort_keys=True, ensure_ascii=False) == json.dumps(b, sort_keys=True, ensure_ascii=False)


def manifest(directory, include_legacy=True):
    return {p.relative_to(directory).as_posix(): sha(p) for p in sorted(directory.rglob("*.json"))
            if include_legacy or p.relative_to(directory).parts[0] != "legacy"}


def pointer_parts(pointer):
    require(isinstance(pointer, str) and pointer.startswith("/"), "Expected a nonempty JSON Pointer")
    tokens = pointer[1:].split("/")
    require(all(not re.search(r"~(?![01])", t) for t in tokens), "Invalid JSON Pointer escape")
    return [t.replace("~1", "/").replace("~0", "~") for t in tokens]


def member(container, token):
    if isinstance(container, list):
        require(re.fullmatch(r"0|[1-9][0-9]*", token) is not None, "Invalid array index: " + token)
        index = int(token)
        require(index < len(container), "JSON Pointer array index is out of bounds")
        return index
    require(isinstance(container, dict) and token in container, "JSON Pointer field is absent: " + token)
    return token


def apply_changes(candidate, raw):
    require(isinstance(raw, dict) and set(raw) == {"changes"}, "Output must contain only changes")
    require(isinstance(raw["changes"], list) and raw["changes"], "changes must be a nonempty array")
    documents = {}
    for number, change in enumerate(raw["changes"]):
        require(isinstance(change, dict) and set(change) == {"file", "op", "path", "value"},
                f"Change {number} must contain file/op/path/value only")
        filename, operation, pointer = change["file"], change["op"], change["path"]
        require(isinstance(filename, str), "file must be a string")
        is_flow = re.fullmatch(r"layered/L4_flow/[A-Za-z0-9_-]+\.json", filename) is not None
        require(filename in (VARIABLES, GROUP) or is_flow, "File outside change whitelist: " + filename)
        target = candidate / filename
        require(target.resolve().is_relative_to(candidate.resolve()), "Output path escapes candidate")
        if operation == "create":
            require(is_flow and pointer == "" and not target.exists() and filename not in documents,
                    "create must introduce a new L4 file with empty path")
            documents[filename] = copy.deepcopy(change["value"])
            continue
        require(operation in ("append", "replace") and filename in (VARIABLES, GROUP),
                "Only append/replace on variables or run_recipe, and create on new L4, are allowed")
        if filename not in documents:
            documents[filename] = read(target)
        tokens = pointer_parts(pointer)
        parent = documents[filename]
        for token in tokens[:-1]:
            parent = parent[member(parent, token)]
        key = member(parent, tokens[-1])
        if operation == "append":
            require(isinstance(parent[key], list) and isinstance(change["value"], list),
                    "append requires an existing array and an array value")
            parent[key].extend(copy.deepcopy(change["value"]))
        else:
            parent[key] = copy.deepcopy(change["value"])
    for filename, document in documents.items():
        write(candidate / filename, document, 4)
    return sorted(documents)


def check_final(candidate, context, original_hashes):
    before, after = read(BASELINE / VARIABLES), read(candidate / VARIABLES)
    require(set(before) == set(after), "System variable keys changed")
    for key in before.keys() - {"production_points", "recipes", "recipe_lookup"}:
        require(identical(before[key], after[key]), "Initial variable changed: " + key)
    require(isinstance(after["production_points"], list) and isinstance(after["recipes"], list), "Expected arrays")
    old_points, old_recipes = len(before["production_points"]), len(before["recipes"])
    require(identical(before["production_points"], after["production_points"][:old_points]), "Old points changed")
    require(identical(before["recipes"], after["recipes"][:old_recipes]), "Old recipes changed")
    require(len(after["recipes"]) == old_recipes + 3, "Exactly three new recipes required")
    engineering = context["new_size_engineering_data"]
    stations, heights = engineering["station_axis_pr"], engineering["z_pr"]
    expected_points = set()
    coordinates = {}
    for flavor in context["flavors"]:
        for station in ("empty", "rinse", "fill", "closure", "code", "finished"):
            xy = stations["fill_by_flavor"][flavor["name"]] if station == "fill" else stations[station]
            for suffix, z in heights.items():
                coordinate = (xy["x"], xy["y"], z)
                coordinates[(flavor["name"], station + "_" + suffix)] = coordinate
                expected_points.add(coordinate)
    new_points = after["production_points"][old_points:]
    for point in new_points:
        require(isinstance(point, dict) and set(point) == {"name", "x", "y", "z"}, "Invalid new point fields")
        require(isinstance(point["name"], str) and bool(point["name"].strip()), "Point needs a name")
        require(all(type(point[a]) is int and 0 <= point[a] <= 15 for a in "xyz"), "PR must be integer 0..15")
    require(Counter(tuple(p[a] for a in "xyz") for p in new_points) == Counter(expected_points),
            "New points differ from supplied engineering coordinates or duplicate shared stations")
    all_ids = [r["id"] for r in after["recipes"]]
    require(len(set(all_ids)) == len(all_ids), "Duplicate recipe IDs")
    new_recipes = after["recipes"][old_recipes:]
    by_flavor = {r["flavor"]: r for r in new_recipes}
    require(set(by_flavor) == {f["name"] for f in context["flavors"]}, "Need one new recipe per flavor")
    require(isinstance(after["recipe_lookup"], list) and len(after["recipe_lookup"]) == 3, "Invalid lookup rows")
    created = set()
    for flavor in context["flavors"]:
        recipe = by_flavor[flavor["name"]]
        require(isinstance(recipe["id"], str) and re.fullmatch(r"[A-Za-z0-9_-]+", recipe["id"]), "Unsafe recipe ID")
        require(set(recipe) == set(before["recipes"][0]), "New recipe fields differ from baseline schema")
        expected = {key: engineering[key] for key in ("volume_ml", "format", "closure_mode", "closure_pr",
                    "infeed_pr", "outfeed_pr", "home_point", "batches", "units_per_batch")}
        rate = flavor["fill_rate_ml_s"]
        expected.update(id=recipe["id"], flavor=flavor["name"], fill_device=flavor["device"],
                        fill_rate_ml_s=rate, fill_time_ms=(1000 * engineering["volume_ml"] + rate - 1) // rate)
        for station in ("empty", "rinse", "fill", "closure", "code", "finished"):
            for suffix in heights:
                key = station + "_" + suffix
                index = recipe[key]
                require(type(index) is int and old_points <= index < len(after["production_points"]),
                        "New recipe point index is invalid: " + key)
                require(tuple(after["production_points"][index][a] for a in "xyz") == coordinates[(flavor["name"], key)],
                        "Wrong engineering point binding: " + flavor["name"] + "/" + key)
                expected[key] = index
        require(identical(recipe, expected), "Recipe differs from frozen requirements: " + recipe["id"])
        row = after["recipe_lookup"][flavor["index"]]
        require(isinstance(row, list) and len(row) == 3 and
                identical(row[:2], before["recipe_lookup"][flavor["index"]]) and
                type(row[2]) is int and row[2] == all_ids.index(recipe["id"]), "Incorrect lookup mapping")
        filename = "layered/L4_flow/" + recipe["id"] + ".json"
        flow = read(candidate / filename)
        require(isinstance(flow, dict) and set(flow) == {"type", "name", "mode", "body"} and
                isinstance(flow["name"], str), "Invalid L4 flow schema")
        expected_flow = {"type": "flow", "name": flow["name"], "mode": "sequence", "body": [
            {"type": "group", "template": "L3_group/run_recipe.group.json", "params": [flavor["index"], 2]}]}
        require(identical(flow, expected_flow), "Incorrect two-parameter L4: " + filename)
        created.add(filename)
    group = read(BASELINE / GROUP)
    group["args"][1]["max"] = 2
    require(identical(group, read(candidate / GROUP)), "L3 changed beyond specification max=2")
    final_hashes = manifest(candidate)
    require(set(final_hashes) == set(original_hashes) | created, "Unexpected created/deleted configuration files")
    for filename, digest in original_hashes.items():
        if filename not in (VARIABLES, GROUP):
            require(final_hashes[filename] == digest, "Frozen baseline file changed: " + filename)
    return new_recipes


def differences(candidate):
    changes, patch = [], []
    baseline_lines = candidate_lines = 0
    for path in sorted(candidate.rglob("*.json")):
        relative = path.relative_to(candidate).as_posix()
        if relative.startswith("legacy/"):
            continue
        original = BASELINE / relative
        a = original.read_text(encoding="utf-8-sig").splitlines(True) if original.exists() else []
        b = path.read_text(encoding="utf-8-sig").splitlines(True)
        baseline_lines += len(a)
        candidate_lines += len(b)
        if a == b:
            continue
        plus = minus = 0
        for tag, i, j, k, l in difflib.SequenceMatcher(a=a, b=b, autojunk=False).get_opcodes():
            if tag != "equal":
                plus += l - k
                minus += j - i
        changes.append({"file": relative, "kind": "modified" if original.exists() else "created",
                        "added_lines": plus, "removed_lines": minus, "net_lines": len(b) - len(a)})
        patch.extend(difflib.unified_diff(a, b, fromfile="baseline/" + relative, tofile="candidate/" + relative))
    return {"baseline_config_lines": baseline_lines, "candidate_config_lines": candidate_lines,
            "net_lines": candidate_lines - baseline_lines, "files": changes}, "".join(patch)


def verify():
    output_base = ROOT / "build/beverage-nl-extension"
    require(output_base.resolve() == output_base and output_base.is_relative_to(ROOT), "Unsafe redirected output directory")
    output_base.mkdir(parents=True, exist_ok=True)
    raw_path = INPUT / "raw_response.json"
    prefix = sha(raw_path)[:12] if raw_path.exists() else "missing-raw"
    output = Path(tempfile.mkdtemp(prefix=prefix + "-", dir=output_base))
    report = {"status": "RUNNING", "started_utc": datetime.now(timezone.utc).isoformat(),
              "output_directory": str(output), "verifier_sha256": sha(__file__),
              "scope": "One newly recorded generation; frozen engineering checks before deterministic simulation. No model output is executed as code or automatically repaired."}
    write(output / "report.json", report)
    try:
        require(__debug__, "Run without python -O; simulator assertions must remain enabled")
        provenance, context = read(INPUT / "provenance.json"), read(INPUT / "context.json")
        input_names = set(provenance["input_sha256"])
        require({"prompt.txt", "context.json"} <= input_names <=
                {"prompt.txt", "context.json", "generator_instruction.txt"}, "Unexpected input hash manifest")
        normalized = provenance["normalized_sha256"]
        require(normalized["normalization"] == "CRLF to LF only" and
                set(normalized["inputs"]) == input_names and
                set(normalized["baseline"]) == set(provenance["baseline_sha256"]) and
                normalized["legacy_references"] == REFERENCE_NORMALIZED_SHA256,
                "Invalid normalized hash manifest")
        hash_checks = {}
        for filename, digest in provenance["input_sha256"].items():
            hash_checks[filename] = frozen_hash(INPUT / filename, digest, normalized["inputs"][filename])
        require(set(manifest(BASELINE, False)) == set(provenance["baseline_sha256"]), "Baseline file set mismatch")
        for filename, digest in provenance["baseline_sha256"].items():
            hash_checks["baseline/" + filename] = frozen_hash(BASELINE / filename, digest, normalized["baseline"][filename])
        hash_checks["raw_response.json"] = frozen_hash(raw_path, provenance["raw_response_sha256"], normalized["raw_response"])
        for filename, document in context["baseline_files"].items():
            require(filename in provenance["baseline_sha256"] and identical(document, read(BASELINE / filename)),
                    "Input context differs from frozen baseline: " + filename)
        original_hashes = manifest(BASELINE)
        report.update(input_sha256=provenance["input_sha256"], baseline_sha256=original_hashes,
                      raw_response_sha256=sha(raw_path), raw_response_recorded_sha256=provenance["raw_response_sha256"],
                      reference_sha256=REFERENCE_SHA256, normalized_sha256=normalized, hash_checks=hash_checks,
                      reference_disclosure=provenance.get("reference_disclosure", ""))
        for filename in sorted(input_names | {"provenance.json", "raw_response.json"}):
            shutil.copyfile(INPUT / filename, output / filename)
        candidate = output / "candidate"
        shutil.copytree(BASELINE, candidate)
        report["applied_files"] = apply_changes(candidate, read(raw_path))
        new_recipes = check_final(candidate, context, original_hashes)
        report["engineering_requirements"] = "PASS"
        change_report, patch = differences(candidate)
        report["changes"] = change_report
        (output / "changes.diff").write_text(patch, encoding="utf-8", newline="\n")
        # Copy only the three evaluator-owned new legacy references. The old six
        # came from the hashed baseline; candidate layer files never come from example5.
        for recipe in new_recipes:
            reference = REFERENCE / (recipe["flavor"] + "_small.json")
            hash_checks["reference/" + recipe["flavor"]] = frozen_hash(reference, REFERENCE_SHA256[recipe["flavor"]],
                                                                     REFERENCE_NORMALIZED_SHA256[recipe["flavor"]])
            shutil.copyfile(reference, candidate / "legacy" / (recipe["id"] + ".json"))
        from simulate_beverage_full import compare, run_pair
        baseline_results = [run_pair(BASELINE, index) for index in range(6)]
        write(output / "baseline_recipes.json", baseline_results)
        simulation = compare(candidate)
        write(output / "candidate_simulation.json", simulation)
        for before, after in zip(baseline_results, simulation["recipes"][:6]):
            require(before["recipe"] == after["recipe"] and before["trace_sha256"] == after["trace_sha256"],
                    "Existing recipe timed trace changed: " + before["recipe"])
        for result in simulation["recipes"][6:]:
            require(result["status"] == "SUCCESS" and result["finished_containers"] == 12 and
                    result["filled_total_ml"] == 3000, "New recipe did not produce twelve 250mL containers")
        require(manifest(BASELINE) == original_hashes, "Baseline changed during verification")
        require(sha(raw_path) == report["raw_response_sha256"], "Raw output changed during verification")
        report.update(status="PASS", baseline_six_traces_unchanged=True,
                      normal_runs=len(simulation["recipes"]), fault_runs=len(simulation["fault_cases"]),
                      new_recipes=[{key: r[key] for key in ("recipe", "status", "finished_containers", "filled_total_ml",
                                                          "stage_counts", "trace_sha256")} for r in simulation["recipes"][6:]])
        write(output / "report.json", report)
        print(json.dumps({"status": "PASS", "report": str(output / "report.json"), "changes": change_report,
                          "normal_runs": report["normal_runs"], "fault_runs": report["fault_runs"],
                          "baseline_six_traces_unchanged": True}, ensure_ascii=False, indent=2))
        return 0
    except Exception as error:
        report.update(status="FAIL", error=type(error).__name__ + ": " + str(error))
        write(output / "report.json", report)
        print("FAIL: " + report["error"] + "\nReport: " + str(output / "report.json"), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(verify())
