"""Freshly verify the twelve-stage beverage data using Python 3.10+ and stdlib.

Run from any working directory. Configuration regeneration compares all bytes
except CRLF/LF line endings, so Git autocrlf does not change the result. Reports
are compared as JSON; the saved extension patch is compared as text with only
newline normalization. Versioned evidence is never overwritten by this command.
"""
import argparse
from datetime import datetime, timezone
import io
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time
import unittest

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "examples/beverage_full"
PHASES = ("example4", "example5")


class VerificationError(Exception):
    """A reproducibility, evidence, or prerequisite check failed."""


def progress(message):
    print(message, flush=True)


def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def write_json(path, value):
    Path(path).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def normalize_newlines(data):
    return data.replace(b"\r\n", b"\n")


def first_difference(actual, expected, path="$"):
    if type(actual) is not type(expected):
        return f"{path}: type {type(actual).__name__} != {type(expected).__name__}"
    if isinstance(actual, dict):
        if actual.keys() != expected.keys():
            return f"{path}: keys differ (fresh-only={sorted(actual.keys() - expected.keys())}, saved-only={sorted(expected.keys() - actual.keys())})"
        for key in actual:
            difference = first_difference(actual[key], expected[key], path + "." + key)
            if difference: return difference
    elif isinstance(actual, list):
        if len(actual) != len(expected): return f"{path}: length {len(actual)} != {len(expected)}"
        for index, (left, right) in enumerate(zip(actual, expected)):
            difference = first_difference(left, right, f"{path}[{index}]")
            if difference: return difference
    elif actual != expected:
        return f"{path}: fresh {actual!r} != saved {expected!r}"
    return ""


def require_equal(actual, expected, label):
    difference = first_difference(actual, expected)
    if difference:
        raise VerificationError(f"{label} is stale or inconsistent: {difference}")


def validate_output(output):
    output = Path(output).resolve()
    protected = [ROOT / name for name in ("examples", "scripts", "src", "include", "tests", "docs", "third_party", ".git")]
    if output == ROOT or any(output == p or output.is_relative_to(p) or p.is_relative_to(output) for p in protected):
        raise VerificationError("Output must be separate from source directories; use build/beverage-verification.")
    return output


def check_regeneration():
    from build_beverage_full import build

    scratch = ROOT / "build"
    scratch.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="beverage-regeneration-", dir=scratch) as temporary:
        generated = Path(temporary) / "generated"
        build(generated, ROOT / "examples/beverage_legacy/beverage_filling_legacy.json")
        count = 0
        for phase in PHASES:
            saved_files = {p.relative_to(SOURCE / phase) for p in (SOURCE / phase).rglob("*.json")}
            rebuilt_files = {p.relative_to(generated / phase) for p in (generated / phase).rglob("*.json")}
            if saved_files != rebuilt_files:
                raise VerificationError(f"{phase}: regenerated configuration file set differs from saved configuration")
            for relative in sorted(saved_files):
                saved = normalize_newlines((SOURCE / phase / relative).read_bytes())
                rebuilt = normalize_newlines((generated / phase / relative).read_bytes())
                if saved != rebuilt:
                    raise VerificationError(f"{phase}/{relative.as_posix()}: regenerated bytes differ (only CRLF/LF is normalized)")
                count += 1
    return count


def physical_counts(phase, report):
    folders = {"legacy": "legacy", "L1": "layered/L1_action", "L2": "layered/L2_node",
               "L3": "layered/L3_group", "L4": "layered/L4_flow"}
    files = {key: sorted((phase / directory).glob("*.json")) for key, directory in folders.items()}
    files.update(devices=[phase / "device_registry.json"], points_and_recipes=[phase / "system_variables.json"])
    actual = {}
    for key, paths in files.items():
        text = [p.read_text(encoding="utf-8") for p in paths]
        actual[key] = {"files": len(paths), "lines": sum(len(s.splitlines()) for s in text),
                       "utf8_bytes": sum(len(s.encode("utf-8")) for s in text)}
    require_equal(actual, report["sizes"], phase.name + " actual file counts")
    return actual


def run_regression_tests(output):
    import test_beverage_full

    suite = unittest.defaultTestLoader.loadTestsFromModule(test_beverage_full)
    count = suite.countTestCases()
    if count < 6: raise VerificationError("Expected at least six full-process regression and negative controls")
    log = io.StringIO()
    result = unittest.TextTestRunner(stream=log, verbosity=2).run(suite)
    (output / "python-tests.log").write_text(log.getvalue(), encoding="utf-8")
    if not result.wasSuccessful():
        raise VerificationError("Full-process regression tests failed; see python-tests.log\n" + log.getvalue())
    return result.testsRun


def cpp_tools():
    found = {name: shutil.which(name) for name in ("cmake", "ctest")}
    missing = [name for name, path in found.items() if path is None]
    if missing:
        raise VerificationError("--cpp requires CMake, CTest, a C++17 compiler and a compatible build tool on PATH. Missing: " + ", ".join(missing))
    return found


def run_cpp(output, tools):
    destination = output / "cpp"
    log_path = output / "cpp-build-and-tests.log"
    pattern = "^beverage_full_(baseline|extended)$"
    commands = [
        ([tools["cmake"], "-S", str(ROOT), "-B", str(destination), "-DBUILD_DEMOS=OFF", "-DBUILD_TESTING=ON", "-DCMAKE_BUILD_TYPE=Release"], ROOT),
        ([tools["cmake"], "--build", str(destination), "--config", "Release", "--target", "test_beverage_full"], ROOT),
    ]
    with log_path.open("w", encoding="utf-8") as log:
        def run(command, cwd):
            log.write("$ " + " ".join(command) + "\n")
            result = subprocess.run(command, cwd=cwd, text=True, encoding="utf-8", errors="replace",
                                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            log.write(result.stdout + "\n")
            log.flush()
            if result.returncode:
                tail = "\n".join(result.stdout.splitlines()[-20:])
                raise VerificationError(f"C++ command failed ({result.returncode}); check C++17 compiler/build-tool setup and {log_path}\n{tail}")
            return result.stdout
        for command, cwd in commands: run(command, cwd)
        inventory = json.loads(run([tools["ctest"], "-C", "Release", "-R", pattern, "--show-only=json-v1"], destination))
        names = sorted(test["name"] for test in inventory["tests"])
        require_equal(names, ["beverage_full_baseline", "beverage_full_extended"], "C++ test discovery")
        run([tools["ctest"], "-C", "Release", "-R", pattern, "--output-on-failure"], destination)
    return {"status": "PASS", "tests": names, "log": str(log_path)}


def verify(output, with_cpp=False):
    from simulate_beverage_full import FAULTS, compare
    from summarize_beverage_full import summarize_data

    output = validate_output(output)
    output.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    evidence = {"status": "RUNNING", "started_utc": datetime.now(timezone.utc).isoformat(),
                "python": sys.version.split()[0], "cpp": {"status": "NOT RUN", "reason": "Use --cpp to build and run the two C++ full-process tests."}}
    write_json(output / "verification.json", evidence)
    try:
        if not __debug__: raise VerificationError("Run without Python -O: model and comparison assertions must remain enabled.")
        tools = cpp_tools() if with_cpp else None
        progress("[1/6] Regenerating configurations and comparing saved bytes (CRLF/LF normalized)...")
        evidence["regenerated_configuration_files"] = check_regeneration()
        progress(f"      {evidence['regenerated_configuration_files']} configuration files match.")
        reports = {}
        for index, phase in enumerate(PHASES, 2):
            progress(f"[{index}/6] Fresh simulation: {phase} ({6 if phase == 'example4' else 9} recipes + {len(FAULTS)} faults)...")
            report = compare(SOURCE / phase)
            write_json(output / (phase + "_simulation.json"), report)
            physical_counts(SOURCE / phase, report)
            require_equal(report, read_json(SOURCE / "reports" / (phase + "_simulation.json")), phase + " simulation report")
            expected_recipes = 6 if phase == "example4" else 9
            if len(report["recipes"]) != expected_recipes or len(report["fault_cases"]) != 11:
                raise VerificationError(phase + ": expected recipe/fault matrix was not executed")
            reports[phase] = report
            progress(f"      PASS: {len(report['recipes'])} normal runs, {len(report['fault_cases'])} faults; complete timed traces and saved reports match.")
        progress("[4/6] Running regression and negative controls...")
        evidence["python_tests"] = run_regression_tests(output)
        progress(f"      {evidence['python_tests']} tests passed.")
        progress("[5/6] Recomputing line counts, template coverage and extension diff from fresh results...")
        comparison, patch = summarize_data(SOURCE, reports)
        write_json(output / "comparison.json", comparison)
        (output / "extension.diff").write_text(patch, encoding="utf-8")
        require_equal(comparison, read_json(SOURCE / "comparison.json"), "comparison.json")
        if normalize_newlines(patch.encode("utf-8")) != normalize_newlines((SOURCE / "extension.diff").read_bytes()):
            raise VerificationError("extension.diff is stale or inconsistent with the actual configuration changes")
        if with_cpp:
            progress("[6/6] Configuring and building C++; running both full-process CTest cases...")
            evidence["cpp"] = run_cpp(output, tools)
        else:
            progress("[6/6] C++ NOT RUN (Python-only data verification; use --cpp to include C++).")
        evidence.update(status="PASS", phases=comparison["phases"], extension=comparison["extension"],
                        normal_runs=sum(len(report["recipes"]) for report in reports.values()),
                        fault_runs=sum(len(report["fault_cases"]) for report in reports.values()),
                        elapsed_seconds=round(time.monotonic() - started, 3))
        write_json(output / "verification.json", evidence)
        progress("\nPASS  phase       recipes  faults  containers  legacy lines  layered lines  reduction")
        for phase in comparison["phases"]:
            progress(f"      {phase['name']:<11} {phase['recipes']:>6}  {len(FAULTS):>6}  {phase['finished_containers']:>10}  "
                     f"{phase['legacy_complete_lines']:>12}  {phase['layered_complete_lines']:>13}  {phase['reduction_percent']:>8.2f}%")
        progress(f"Fresh evidence: {output}\nC++: {evidence['cpp']['status']}; elapsed: {evidence['elapsed_seconds']:.1f}s")
        return evidence
    except Exception as error:
        evidence.update(status="FAIL", error=str(error), elapsed_seconds=round(time.monotonic() - started, 3))
        write_json(output / "verification.json", evidence)
        raise


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, default=ROOT / "build/beverage-verification",
                        help="fresh evidence directory (default: repository build/beverage-verification)")
    parser.add_argument("--cpp", action="store_true",
                        help="also configure/build with CMake and run both full-process CTest cases; requires CMake/CTest and a C++17 toolchain")
    args = parser.parse_args(argv)
    if sys.version_info < (3, 10):
        parser.exit(2, "Python 3.10 or newer is required.\n")
    try:
        verify(args.output, args.cpp)
    except (VerificationError, AssertionError, OSError, ValueError, KeyError) as error:
        print("FAIL: " + (str(error) or type(error).__name__), file=sys.stderr, flush=True)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
